### ISSUE TITLE
"File Locking and Error Handling Needed for Concurrent Access to Excel File in Flask App"

### ISSUE THREAD

**Issue by sakshipowar1612** [sakshipowar1612/SE_Assignment_8-#3]
In my Flask web application, I am using an Excel file (data.xlsx) to store form submissions. The application works well when there are few or single users. However, when multiple users submit the form at the same time, there is a risk of concurrent access to the Excel file, which can lead to data corruption or overwriting issues.

Additionally, there is no error handling to manage potential problems when accessing or writing to the file, which can cause the application to fail silently or throw unexpected errors.

Proposed Solution:

Implement file locking to prevent multiple writes at the same time.
Add error handling to ensure the application manages file I/O issues more gracefully.
Optionally consider using a database (SQLite, MySQL, etc.) for handling data storage in a multi-user environment, which would improve scalability and avoid file access issues.
Steps to Reproduce:

Set up a Flask app that writes form submissions to an Excel file using pandas.
Have multiple users submit the form simultaneously.
Observe potential errors or file corruption issues due to concurrent writes.

**Comment by sakshipowar1612** [comment]
> In my Flask web application, I am using an Excel file (data.xlsx) to store form submissions. The application works well when there are few or single users. However, when multiple users submit the form at the same time, there is a risk of concurrent access to the Excel file, which can lead to data corruption or overwriting issues.
> 
> Additionally, there is no error handling to manage potential problems when accessing or writing to the file, which can cause the application to fail silently or throw unexpected errors.
> 
> Proposed Solution:
> 
> Implement file locking to prevent multiple writes at the same time. Add error handling to ensure the application manages file I/O issues more gracefully. Optionally consider using a database (SQLite, MySQL, etc.) for handling data storage in a multi-user environment, which would improve scalability and avoid file access issues. Steps to Reproduce:
> 
> Set up a Flask app that writes form submissions to an Excel file using pandas. Have multiple users submit the form simultaneously. Observe potential errors or file corruption issues due to concurrent writes.

**Comment by MNP2003** [comment]
2 issue resolve
