### ISSUE TITLE
README Update: Add Detailed Setup and Usage Instructions

### ISSUE THREAD

**Issue by sakshipowar1612** [sakshipowar1612/SE_Assignment_8-#5]
The current README provides a good overview of the project and its features, but it's missing detailed instructions on how to set up and run the project locally. For new users or contributors, adding a comprehensive setup guide would be helpful.
Suggested Changes:

### **Add a "Setup" section to the README that includes:**
**Steps for cloning the repository:**
Example:
git clone https://github.com/[your-repo-name].git
**Instructions for installing dependencies:**
Mention any package managers and dependencies that need to be installed, for example:
pip install -r requirements.txt
**Steps to run the Flask app:**
Provide instructions to run the project locally, like:
flask run
Add a "Usage" section that includes:

    Brief information about the available features, and how users can interact with the system (e.g., submitting forms).
    Example of the expected output when the app is running successfully.

**Optional Enhancements:**

    Consider adding a Contributing section with guidelines on how users can submit issues, contribute to the project, and open pull requests.

**Comment by MNP2003** [comment]
1 issues resolve
